using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SSS.UserInterface.Widgets;

[GenerateTypedNameReferences]
public sealed partial class SSSStatusGui : UIWidget
{
    public SSSStatusGui()
    {
        RobustXamlLoader.Load(this);
    }
}
