using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SSS.UserInterface.Widgets;

[GenerateTypedNameReferences]
public sealed partial class SSSStatusGui : UIWidget
{
    private readonly StyleBoxTexture _roleStyleBox;

    public SSSStatusGui()
    {
        RobustXamlLoader.Load(this);

        var resourceCache = IoCManager.Resolve<IResourceCache>();

        var styleBox = new StyleBoxTexture()
        {
            Texture = resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png"),
        };
        styleBox.SetPatchMargin(StyleBox.Margin.All, 10);
        _roleStyleBox = styleBox;
    }

    public void SetHealthBar(string text, float value, float maxValue)
    {
        HealthNumber.Text = text;
        HealthBar.MaxValue = maxValue;
        HealthBar.Value = value;
    }

    public void SetRole(string role, Color color)
    {
        RoleBG.PanelOverride = new StyleBoxTexture(_roleStyleBox) { Modulate = color };
        RoleText.Text = role;
    }
}
